### ISSUE TITLE
User's password can be hashed before sending it to the server

### ISSUE THREAD

**Issue by imadelh** [hudikhq/hoodik#109]
If my understanding is correct, when a user is created or during login, the raw password is sent to the server. The password is then hashed (server side) and compared to the stored password from DB.

There is a security risk associated with this model, and a better approach would be to hash the password on client side, and for authentication the hash would be sent to the server for validation.

On the client side, you can keep using the raw password to decrypt the retrieved private key.

This model would ensure that the server (or anything on-path) never get access to the raw password.

Thanks.

**Comment by taladar** [comment]
On the other hand your model prevents ever changing the hash algorithm transparently when the old one becomes too fast for modern devices.

**Comment by skalmn** [comment]
How would the server validate said hash without the plain text password? I mean this is an issue on all of the internet basically, it can only be validated if the hashing algorithm doesn't use a random salt. And at that point you've compromised the security enough to not make it worth it.

**Comment by htunlogic** [comment]
As @skalmn already mentioned, this is just the way web services work, and it has to be implemented this way in order to have a random salt. Sending plain text passwords to the server shouldn't be a problem if your applications use HTTPS.

**Comment by supercooltest2024** [comment]
There is no reason why the server can't rehash a hashed password. Nor is it impossible to update the client hashing algorithm.

The current problem is that a fixed known version good client (like a mobile app or the web frontend if a extension guards updates) still must trust the server. Sending the password to the server directly means a compromised server will be able to decrypt the private key.

The proposed solution, by @imadelh, for the client to hash the password means that the server will only ever see the hashed password which cannot be used to decrypt the private key. This means trusted clients don't need to trust the server. This is a desirable quality for an e2ee solution. This solution means that to the server, the client-password-hash is effectively the password; the server should still rehash it with a salt.

The concern about the hash being unable to change the client hashing algorithm, by @taladar, can be solved by making the login process multi-step. After providing username, the server could return what client side hashing algorithm is currently in use for the account so that the client can use that algorithm on the password to complete the login request. For accounts that don't exist, returning an arbitrary client side hashing algorithm could prevent probing usernames. After login, the client could update their password hash with a new client side hashing algorithm and send the new hash to the server.

The concern about the client not being able to salt the client side hashed password, by @skalmn and @htunlogic , is that without salting a rogue server could use a rainbow table to find the true password given the client side hash (assuming the true password is in a rainbow table). But client hashing is still desirable, as if a password is not in a rainbow table (if randomly generated and not reused) then salting isn't necessary.

A possible concern is that if the server treats a client side hash as the password, then any collisions on the client side hash are also the password. It isn't really clear how an attacker would get a client side hash though. But even if an attacker did get the client side hash and was thus able to log in, they wouldn't be able to decrypt the private key without the real password. So they wouldn't be able to access anything besides file metadata and directory structure. And we could prevent that by extending the login process further. After providing a correct client side hash to the server which checks against the salted hash of that hash; the server could then issue a challenge via the public key and send the client the encrypted private key. The client would need to be able to decrypt the private key to complete the challenge.

To sum up: Sending plain text passwords to the server IS a problem EVEN IF your applications use HTTPS. E2EE solutions shouldn't trust the server. The new login process could look like the following:
* User types in username and password.
* Client sends the username to the server `GetClientHashingAlgorithmForUser(username) -> ClientSideHashingAlgorithm`
* Server returns what algorithm that user last used to hash their password for the server
* Client uses ClientSideHashingAlgorithm to hash the password
* Client sends login request to server `Login(username,ClientSideHashedPassword) -> Option<(EncryptedPrivateKey,Challenge)>`
* The server gets the ServerSideHash, PubKey, EncryptedPrivateKey for the given username from the database
* The server verifies ClientSideHashedPassword against ServerSideHash (the ServerSideHash is a salted and hashed version of the ClientSideHashedPassword).
* If successful the server generates a random string as a challenge. and sends it a to the client
* The client decrypts the EncryptedPrivateKey with the password
* The client signs the challenge with the PrivateKey and sends it to the server `CompleteLogin(SignedChallenge,Challenge) -> Option<UserData>`
* The server validates the SignedChallenge with the user's PubKey.
* If successful the users session is upgraded to signed in.
* If there is a new suggested ClientSideHashingAlgorithm, the client can update their hash by sending `UpdateClientSideHashedPassword(ClientSideHashedPassword,ClientSideHashingAlgorithm)`

For backward compatibility, existing accounts would get a ClientSideHashingAlgorithm of None. Then when they next logged in, their client would be able to update their password to an additionally client side hashed version.

```
Client                                                  Server
  │                                                        │
  │─── 1. GetClientHashingAlgorithm(username) ────────────>│
  │<── 2. Returns Algorithm (e.g., Argon2id) ──────────────│
  │                                                        │
  │ [Hashes raw password locally with algorithm]          │
  │                                                        │
  │─── 3. Login(username, ClientSideHashedPassword) ──────>│
  │                                                        │ [Verifies against ServerSideHash]
  │<── 4. Returns EncryptedPrivateKey + Challenge ─────────│
  │                                                        │
  │ [Decrypts RSA Private Key using raw password]         │
  │ [Signs Challenge with RSA Private Key]                 │
  │                                                        │
  │─── 5. CompleteLogin(SignedChallenge) ─────────────────>│
  │                                                        │ [Validates signature with PubKey]
  │<── 6. Session Upgraded to Authorized ──────────────────│
```

Implementation guide LVL1. Instantly benefit with little effort.
* Server
  * The user table is updated to include a ClientSideHashingAlgorithm column. Default existing users to None.
  * New public endpoint `GetClientHashingAlgorithmForUser(username) -> ClientSideHashingAlgorithm`
    * For non-existant users, should return a deterministically chosen ClientSideHashingAlgorithm. To prevent username probing.
  * New private endpoint `UpdateClientSideHashedPassword(ClientSideHashedPassword,ClientSideHashingAlgorithm)`
    * The server does not care what the ClientSideHashingAlgorithm is, besides storing it.
    * This does not change the private key
    * This does change the user's password in the db using the same salt hashing system already in use. (just treat ClientSideHashedPassword as a regular password).
  * Update the NewUser flow to take a ClientSideHashingAlgorithm.
* Client
  * When making a new account fill out the ClientSideHashingAlgorithm with the latest suggested algorithm (hardcoded in client).
  * Before logging in, send GetClientHashingAlgorithmForUser. Use that algorithm (could be none) to hash the password. Then complete the login flow normally (but with the hashed password).
  * After logging in, if the previous algorithm is not the latest suggested (e.g. None), then hash the password with the latest suggested and send UpdateClientSideHashedPassword.

Implementation guide LVL2. After the above, to protect against potential client hash collisions providing access to user metadata.
* On the user session object, track a new variable ChallengeState. This is either a challenge string or Success.
* When a user completes the existing login flow, generate a challenge string and send to client along with the encrypted private key.
* The client can then sign the challenge and call CompleteLogin which will change the ChallengeState to Success.
* Lock endpoints behind ChallengeState Success (for compatibility with legacy clients, this could come later).

Implementation guide LVL3. After the above, implement a web extension to verify frontend files are developer signed.

**Comment by htunlogic** [comment]
@supercooltest2024 agreed, and as of v2 this is done via OPAQUE, the password no longer reaches the server in any form.
