### ISSUE TITLE
Auth Question/Enhancement

### ISSUE THREAD

**Issue by MegaShinySnivy** [hudikhq/hoodik#61]
How is authentication and user creation handled within Hoodik? Is it possible to disable account creation and instead just use OAuth or SAML instead? I tried to look through the docs and I didn't see anything.

**Comment by htunlogic** [comment]
User registration can be completely disabled or restricted:
 - There are options to add whitelist, or blacklist rules for emails which will allow or deny users registering. 
 - Fully disabling registration will only allow users that have received an invite via email to register.

Although, keep in mind that for using the invitation system you will have to configure SMTP sender through the environment variables. 

Oauth and SAML are not planned yet and probably won't be feasible because of the private key that is generated once the user is registered. But there is always a maybe.
