### ISSUE TITLE
Error accessing outside of localhost

### ISSUE THREAD

**Issue by jabuxas** [hudikhq/hoodik#97]
Running on localhost, everything runs fine. If I hop on another device, I get the error:

```Request 'GET https://10.10.10.108:4554/api/links?with_expired=true' failed with status 401 auth::data::claims|no_claims```

docker-compose.yml
```
version: "3"

services:
  hoodik:
    container_name: hoodik
    image: hudik/hoodik:v1.1.2
    ports:
      - "4554:5443"
    volumes:
      - ./data:/data
    environment:
      DATA_DIR: /data
      APP_URL: "https://localhost:4554/"```
      
      
Changing APP_URL to 0.0.0.0 doesn't seem to do anything.

**Comment by htunlogic** [comment]
Hey, the problem is with the cookie domain. Once you log in, the application sets a cookie on the app domain that you use. So, if you set your cookie domain as `localhost,` you will only be able to use the application locally, and if you set it to your outside address, you will only be able to use it through your outside domain.

Technically, you could access it from the outside, but that is not practical inside your network.

So, in order to access it from outside and inside your network, you would have to use the same address. The best way to achieve that is to properly route it to the outside world through a reverse proxy, and then internally, through your DNS settings, tell your network that the address used for it is located inside your network.

In my setup, I have Ngnix Proxy Manager, which exposes it as `hoodik.mydomain.com`, and my DNS Pi-Hole knows that `mydomain.com` should point to my Ngnix Proxy Manager. You don't need to have Pi-Hole; some routers also allow you to achieve that.
